import { existsSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { isDevSource } from '../dev-source'
import type { NavItem } from '../types'

export const NAV_TYPES_FILE_NAME = 'foundry-nav.gen.d.ts'

/**
 * Picks where the generated types land.
 *
 * A type augmentation only applies if TypeScript actually loads the file, and
 * the common Vite tsconfig ships `"include": ["src"]`, which silently skips
 * anything at the project root. So prefer `src/` when it exists, matching how
 * TanStack Router places its generated route tree, and fall back to the root
 * for projects laid out differently.
 */
export function resolveNavTypesPath(userRoot: string): string {
  const srcDir = resolve(userRoot, 'src')
  const dir = existsSync(srcDir) ? srcDir : userRoot

  return resolve(dir, NAV_TYPES_FILE_NAME)
}

/**
 * Walks the nav tree depth first, emitting every path prefix.
 *
 * Parents are addressable, not just leaves, so a preview can sit directly on
 * `'Forms'` as well as on `'Forms/Button'`.
 */
export function flattenNavPaths(nav: NavItem[] | undefined, prefix = ''): string[] {
  if (!nav?.length) return []

  return nav.flatMap((item) => {
    const path = prefix ? `${prefix}/${item.label}` : item.label
    return [path, ...flattenNavPaths(item.children, path)]
  })
}

/**
 * Generates the type augmentation that turns `NavPath` into a union of the
 * paths declared in the user's config.
 *
 * Written into the user's project rather than the cache directory so their
 * editor and `tsc` both pick it up without extra configuration. Regenerated on
 * every server start and whenever the config changes; meant to be gitignored.
 */
export function writeNavTypes(nav: NavItem[] | undefined, userRoot: string): string {
  const paths = flattenNavPaths(nav)

  // With nothing declared, NavPath stays `string` so previews still typecheck.
  const navPath = paths.length
    ? paths.map((path) => JSON.stringify(path)).join(' | ')
    : 'string'

  // Augment the module the consumer imports `NavPath` from: `react-foundry` when
  // installed, the internal `@react-foundry/core` for the in-monorepo demo. Both resolve
  // to the same `Register` symbol (react-foundry re-exports it), so the augmentation
  // merges either way.
  const moduleName = isDevSource() ? '@react-foundry/core' : 'react-foundry'

  const filePath = resolveNavTypesPath(userRoot)
  const content = [
    '// Generated by react-foundry. Do not edit.',
    '// Regenerated from the `nav` tree in your foundry config on every start.',
    '',
    `declare module '${moduleName}' {`,
    '  interface Register {',
    `    navPath: ${navPath}`,
    '  }',
    '}',
    '',
    '// Marks this file as a module, which module augmentation requires.',
    'export {}',
    '',
  ].join('\n')

  writeFileSync(filePath, content, 'utf-8')
  return filePath
}
