import { existsSync, rmSync, writeFileSync } from 'node:fs'
import { relative, resolve } from 'node:path'

import { DEFAULT_CONFIG } from '../config/defaults'
import type { NavItem } from '../types'
import { globBaseDir, resolvePreviewsGlob } from './virtual-module-plugin'

export const NAV_TYPES_FILE_NAME = 'foundry-nav.gen.d.ts'

/** Where the generated types can be pinned or inferred from. */
export interface NavTypesLocation {
  /** Previews glob, used to infer the output dir when they live in another package. */
  previews?: string
  /** Explicit output file path (resolved against root), overriding inference. */
  navTypesPath?: string
}

/** True when `target` is not contained within `base`. */
function isOutside(base: string, target: string): boolean {
  const rel = relative(base, target)
  return rel === '' ? false : rel.startsWith('..') || resolve(base, rel) !== target
}

/**
 * Picks where the generated types land.
 *
 * A type augmentation only applies if TypeScript actually loads the file in the
 * same compilation as the previews. Three cases, in order of precedence:
 *
 * 1. `navTypesPath` pins the exact file, for layouts the heuristic can't guess.
 * 2. When the previews live in another package (their glob base resolves outside
 *    root, the normal monorepo case), write next to them so that package's
 *    tsconfig picks the augmentation up. The base already includes the previews'
 *    own `src`, so we don't re-append one.
 * 3. Otherwise keep the historical single-package behavior: prefer `<root>/src`
 *    when it exists (the common Vite tsconfig ships `"include": ["src"]`, which
 *    silently skips the project root), else fall back to `<root>`.
 */
export function resolveNavTypesPath(
  userRoot: string,
  { previews, navTypesPath }: NavTypesLocation = {}
): string {
  if (navTypesPath) return resolve(userRoot, navTypesPath)

  const base = globBaseDir(
    resolvePreviewsGlob(previews ?? DEFAULT_CONFIG.previews, userRoot)
  )
  if (isOutside(userRoot, base)) return resolve(base, NAV_TYPES_FILE_NAME)

  const srcDir = resolve(userRoot, 'src')
  const dir = existsSync(srcDir) ? srcDir : userRoot

  return resolve(dir, NAV_TYPES_FILE_NAME)
}

/**
 * Walks the nav tree depth first, emitting every path prefix.
 *
 * Parents are addressable, not just leaves, so a preview can sit directly on
 * `'Forms'` as well as on `'Forms/Button'`.
 */
export function flattenNavPaths(
  nav: readonly NavItem[] | undefined,
  prefix = ''
): string[] {
  if (!nav?.length) return []

  return nav.flatMap((item) => {
    const path = prefix ? `${prefix}/${item.label}` : item.label
    return [path, ...flattenNavPaths(item.children, path)]
  })
}

/**
 * Generates the type augmentation that turns `NavPath` into a union of the
 * paths declared in the user's config, returning where it landed.
 *
 * Written into the user's project rather than the cache directory so their
 * editor and `tsc` both pick it up without extra configuration. Regenerated on
 * every server start and whenever the config changes; meant to be gitignored.
 *
 * Returns null when there is no tree to describe, having removed any file a
 * previous run left behind.
 */
export function writeNavTypes(
  nav: readonly NavItem[] | undefined,
  userRoot: string,
  location: NavTypesLocation = {}
): string | null {
  const filePath = resolveNavTypesPath(userRoot, location)
  const paths = flattenNavPaths(nav)

  // An undeclared tree would emit `navPath: string`, which is exactly what
  // ResolveNavPath already falls back to with no augmentation present. The file
  // would change nothing while still needing a gitignore entry, so remove it
  // instead of writing it. Removing rather than merely skipping matters: a project
  // that drops its `nav` would otherwise keep the previous union pinned by a stale
  // file, with no sign of where it came from.
  if (paths.length === 0) {
    if (existsSync(filePath)) rmSync(filePath)
    return null
  }

  // Augment the module everyone imports `NavPath` from: `react-foundry`. The published
  // `dist/index.d.ts` declares `Register` locally (the dts bundler inlines it), so the
  // augmentation merges into it and narrows `NavPath`. The in-monorepo demo imports from
  // `react-foundry` too, so it exercises this exact path.
  const moduleName = 'react-foundry'

  // One member per line, and every string through JSON.stringify so the module name
  // and the paths quote alike. A single-line union runs to hundreds of columns on a
  // real tree, which trips `max-len` and Prettier's `printWidth` in the consumer's
  // project even though the file is generated.
  const members = paths.map((path) => `\n      | ${JSON.stringify(path)}`).join('')

  const content = [
    // Generated files exempt themselves rather than expecting every consumer to
    // configure around them, the way TanStack Router's `routeTree.gen.ts` does.
    '/* eslint-disable */',
    '// Generated by react-foundry. Do not edit.',
    '// Regenerated from the `nav` tree in your foundry config on every start.',
    '',
    // Applies to the declaration that follows, so it has to be the last line before it.
    '// prettier-ignore',
    `declare module ${JSON.stringify(moduleName)} {`,
    '  interface Register {',
    `    navPath:${members}`,
    '  }',
    '}',
    '',
    '// Marks this file as a module, which module augmentation requires.',
    'export {}',
    '',
  ].join('\n')

  writeFileSync(filePath, content, 'utf-8')
  return filePath
}
