/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentIdVariantVariantNameRouteImport } from './routes/$componentId.variant.$variantName'
import { Route as ComponentIdDemoDemoNameRouteImport } from './routes/$componentId.demo.$demoName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentIdVariantVariantNameRoute =
  ComponentIdVariantVariantNameRouteImport.update({
    id: '/$componentId/variant/$variantName',
    path: '/$componentId/variant/$variantName',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentIdDemoDemoNameRoute = ComponentIdDemoDemoNameRouteImport.update({
  id: '/$componentId/demo/$demoName',
  path: '/$componentId/demo/$demoName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$componentId/demo/$demoName': typeof ComponentIdDemoDemoNameRoute
  '/$componentId/variant/$variantName': typeof ComponentIdVariantVariantNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$componentId/demo/$demoName': typeof ComponentIdDemoDemoNameRoute
  '/$componentId/variant/$variantName': typeof ComponentIdVariantVariantNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$componentId/demo/$demoName': typeof ComponentIdDemoDemoNameRoute
  '/$componentId/variant/$variantName': typeof ComponentIdVariantVariantNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$componentId/demo/$demoName'
    | '/$componentId/variant/$variantName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$componentId/demo/$demoName'
    | '/$componentId/variant/$variantName'
  id:
    | '__root__'
    | '/'
    | '/$componentId/demo/$demoName'
    | '/$componentId/variant/$variantName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentIdDemoDemoNameRoute: typeof ComponentIdDemoDemoNameRoute
  ComponentIdVariantVariantNameRoute: typeof ComponentIdVariantVariantNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$componentId/variant/$variantName': {
      id: '/$componentId/variant/$variantName'
      path: '/$componentId/variant/$variantName'
      fullPath: '/$componentId/variant/$variantName'
      preLoaderRoute: typeof ComponentIdVariantVariantNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$componentId/demo/$demoName': {
      id: '/$componentId/demo/$demoName'
      path: '/$componentId/demo/$demoName'
      fullPath: '/$componentId/demo/$demoName'
      preLoaderRoute: typeof ComponentIdDemoDemoNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentIdDemoDemoNameRoute: ComponentIdDemoDemoNameRoute,
  ComponentIdVariantVariantNameRoute: ComponentIdVariantVariantNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
